<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="/css/main.css">
        <link rel="stylesheet" href="/css/remove-tapir.css">
        <title>clayton</title>
    </head>
    <body>
        <div class="content">
            <p>The tapir is nothing more than a plague to Gün Platoon.</p>
            <p><b>YOU</b> can do your part in removing the tapir. Tag <b>@Treekii#0373</b> and let him know that his first priority should be to exterminate the tapir, once and for all.</p>
            
            <div class="images">
                <div class="column">
                    <img src="/images/remove-tapir/1.png"></img>
                    <img src="/images/remove-tapir/2.gif"></img>
                    <img src="/images/remove-tapir/3.gif"></img>
                    <img src="/images/remove-tapir/4.gif"></img>
                    <img src="/images/remove-tapir/5.jpg"></img>
                    <img src="/images/remove-tapir/6.png"></img>
                </div>
                <div class="column">
                    <img src="/images/remove-tapir/7.png"></img>
                    <img src="/images/remove-tapir/8.png"></img>
                    <img src="/images/remove-tapir/9.png"></img>
                    <img src="/images/remove-tapir/a.png"></img>
                    <img src="/images/remove-tapir/b.png"></img>
                </div>
            </div>
        </div>
    </body>
</html>
